#!/bin/sh
CURDIR=$(cd $(dirname $0) && pwd)
smbconf_def="$CURDIR/conf/smb.def"
CONFIDR="$CURDIR/conf"
PACKAGEID="com.modouwifi.samba"
# to tp
TO_TP_TITLE="魔豆文件共享"
TO_TP_CONF_DIR="/data/conf/launcher/conf.d"
TO_TP_CONF_FILE="$TO_TP_CONF_DIR/samba_share.conf"
TO_TP_ICON="$CURDIR/res/icon.png"
TO_TP_PRESSED_ICON="$CURDIR/res/picon.png"
PIDFILE="$CURDIR/custom.pid"
SMBSTATUSFILE="$CURDIR/conf/smb.status"

usage()
{
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}


install()
{
    # to tp
    if [ ! -d $TO_TP_CONF_DIR ]; then
        mkdir -p $TO_TP_CONF_DIR
    fi
    echo "{" > "$TO_TP_CONF_FILE"
    echo "\"name\" :  \"$TO_TP_TITLE\"," >> "$TO_TP_CONF_FILE"
    echo "\"icon\" : \"$TO_TP_ICON\"," >> "$TO_TP_CONF_FILE"
    echo "\"iconPressed\" : \"$TO_TP_PRESSED_ICON\"," >> "$TO_TP_CONF_FILE"
    echo "\"exec\" : \"$CURDIR/sbin/smb-action.sh tpstart\"," >> "$TO_TP_CONF_FILE"
    echo "\"msgNum\" : 4" >> "$TO_TP_CONF_FILE"
    echo "}" >> "$TO_TP_CONF_FILE"
    return 0;
}


uninstall()
{
    rm  /lib/libbigballofmud.so.0
    rm  $TO_TP_CONF_FILE
    echo "uninstall";
    return 0;
}


stop()
{
    $CURDIR/sbin/smb-server.sh stop
    /system/sbin/appInfo.sh set_status $PACKAGEID NOTRUNNING
    echo 0 > $SMBSTATUSFILE
    return 0;
}


start()
{
    $CURDIR/sbin/smb-server.sh start
    /system/sbin/appInfo.sh set_status $PACKAGEID ISRUNNING
    echo 1 > $SMBSTATUSFILE
    return 0;
}


status()
{
    echo "Hello, modou";
    return 0;
}

set_config()
{
    $CURDIR/sbin/smb-server.sh syncConfig
    $CURDIR/sbin/smb-server.sh stop
    $CURDIR/sbin/smb-server.sh start
    $CURDIR/sbin/smb-server.sh flush
    /system/sbin/appInfo.sh set_status $PACKAGEID ISRUNNING
    return 0;
}


# main
if [ $# -lt 1 ]; then
    usage init
    exit 1
fi


case "$1" in
    "stop")
        stop;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "start")
        start;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "status")
        status;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "set_config")
        set_config;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "install")
        install;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "uninstall")
        uninstall;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    *)
        usage init;
        exit 1;
        ;;
esac
